environment:
  APPVEYOR_YML_DISABLE_PS_LINUX: true
  NuGetApiKey:
    secure: Ocp1ATd6eZ0eY9+LfZ9Stp9/J1B5eFdBPMdaTRWVa4xh6/NV45ZBYtU5+eemrTWt
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      PSVersion: Core
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      PSVersion: Windows

matrix:
  fast_finish: true

skip_commits:
  message: /updated readme.*|update readme.*s|\[skip ci\]|\[ci skip\]/

only_commits:
  message: /!deploy|!build|!ci|\[ci\]/

build: off

test_script:
  - ps:   if ($env:PSVersion -eq 'Windows') { . .\build.ps1 -Task Publish }
  - pwsh: if ($env:PSVersion -eq 'Core') {. .\build.ps1 -Task Test }